
-- | Поле         | Тип (PostgreSQL)                          | Обязательное | Описание                                                |
-- | ------------ | ----------------------------------------- | ------------ | ------------------------------------------------------- |
-- | `id`         | `BIGINT GENERATED BY DEFAULT AS IDENTITY` | ✔            | PK — уникальный идентификатор узла                      |
-- | `parent_id`  | `BIGINT`                                  | ✖            | FK → `equipment.id`, родительский узел (NULL для корня) |
-- | `name`       | `VARCHAR(255)`                            | ✔            | Проектное / системное наименование                      |
-- | `title`      | `VARCHAR(500)`                            | ✔            | Человеческое название                                   |
-- | `status`     | `equipment_status`                        | ✔            | Статус: `Active` / `Archived`                           |
-- | `created`    | `TIMESTAMPTZ`                             | ✔            | Дата создания записи                                    |
-- | `updated`    | `TIMESTAMPTZ`                             | ✔            | Дата последнего изменения                               |


-- Дерево оборудования
CREATE TABLE IF NOT EXISTS equipment (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    -- Уникальный идентификатор
    parent_id   BIGINT,                 -- Идентификатор родительской ноды
    attributes  jsonb                   -- Характеристики оборудования
    
    pid         int4 NOT NULL REFERENCES public.tags(id),          -- Идентификатор источника (процесс / параметр / сигнал)
    value       int2 NOT NULL,          -- Значение сигнала (0 = Норма, >0 = Авария)
    status      int2 NOT NULL           -- Статус сигнала процесса (0 - Норма, 10 - Недостоверно) (иными словами качество сигнала)
); 

-- Каталог докумментов для оборудования и других сущностей
CR
EATE TABLE IF NOT EXISTS documents (

);
