
-- | Поле         | Тип (PostgreSQL)                          | Обязательное | Описание                                                |
-- | ------------ | ----------------------------------------- | ------------ | ------------------------------------------------------- |
-- | `id`         | `BIGINT GENERATED BY DEFAULT AS IDENTITY` | ✔            | PK — уникальный идентификатор узла                      |
-- | `parent_id`  | `BIGINT`                                  | ✖            | FK → `equipment.id`, родительский узел (NULL для корня) |
-- | `name`       | `VARCHAR(255)`                            | ✔            | Проектное / системное наименование                      |
-- | `title`      | `VARCHAR(500)`                            | ✔            | Человеческое название                                   |
-- | `wear`       | `equipment_status`                        | ✔            | Статус: `Active` / `Archived`                           |
-- | `status`     | `equipment_status`                        | ✔            | Статус: `Active` / `Archived`                           |
-- | `created`    | `TIMESTAMPTZ`                             | ✔            | Дата создания записи                                    |
-- | `updated`    | `TIMESTAMPTZ`                             | ✔            | Дата последнего изменения                               |

-- Статус оборудования
DO $$
BEGIN
    if not exists (SELECT 1 FROM pg_type WHERE typname = 'equipment_status') THEN
        CREATE TYPE public."equipment_status" AS ENUM (
            'Active',       -- участвует
            'Archived',     -- скрыт / не используется
        );
    end if;
END
$$;


-- Дерево оборудования
CREATE TABLE IF NOT EXISTS equipment (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    -- Уникальный идентификатор
    parent_id   BIGINT REFERENCES equipment(id),            -- Идентификатор родительской ноды
    name        VARCHAR(255) NOT NULL,                      -- Проектное / Системное имя устройста, уникальное как минимум в пределах родителя
    title       VARCHAR(500) NOT NULL,                      -- Название для UI, не требует перевода, поскольку задано пользователем
    status      equipment_status NOT NULL DEFAULT 'Active', -- Статус: `Active` / `Archived`
    attributes  jsonb,                                      -- Характеристики оборудования
    created     TIMESTAMPTZ NOT NULL DEFAULT Now(),         -- Дата создания записи (сомнительно, можем записать в логи факт создания, если это вообще надо)
); 

-- Тип значения Характеристик оборудования
DO $$
BEGIN
    if not exists (SELECT 1 FROM pg_type WHERE typname = 'equipment_attribute_type') THEN
        CREATE TYPE public."equipment_attribute_type" AS ENUM (
            'string',
            'number',
            'boolean',
            'date',
            'json'
        );
    end if;
END
$$;

-- Характеристики оборудования
CREATE TABLE IF NOT EXISTS  equipment_attribute (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    -- Уникальный идентификатор
    equipment_id    BIGINT NOT NULL REFERENCES equipment(id),               -- указывает на принадлежность Equipment
    key             VARCHAR(255) NOT NULL,                                  -- Уникальный в пределах equipment_id
    type            equipment_attribute_type NOT NULL,                      -- Тип значения string', 'number', 'boolean', 'date', 'json'
    value           TEXT,                                                   -- Значение
);

-- Каталог докумментов оборудования
CREATE TABLE IF NOT EXISTS documents (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    -- Уникальный идентификатор
    equipment_id    BIGINT NOT NULL REFERENCES equipment(id),     -- указывает на принадлежность оборудованию
);
