
-- | Поле         | Тип (PostgreSQL)                          | Обязательное | Описание                                                |
-- | ------------ | ----------------------------------------- | ------------ | ------------------------------------------------------- |
-- | `id`         | `BIGINT GENERATED BY DEFAULT AS IDENTITY` | ✔            | PK — уникальный идентификатор узла                      |
-- | `parent_id`  | `BIGINT`                                  | ✖            | FK → `equipment.id`, родительский узел (NULL для корня) |
-- | `name`       | `VARCHAR(255)`                            | ✔            | Проектное / системное наименование                      |
-- | `title`      | `VARCHAR(500)`                            | ✔            | Человеческое название                                   |
-- | `status`     | `equipment_status`                        | ✔            | Статус: `Active` / `Archived`                           |
-- | `created`    | `TIMESTAMPTZ`                             | ✔            | Дата создания записи                                    |
-- | `updated`    | `TIMESTAMPTZ`                             | ✔            | Дата последнего изменения                               |

-- Статус оборудования
DO $$
BEGIN
    if not exists (SELECT 1 FROM pg_type WHERE typname = 'equipment_status') THEN
        CREATE TYPE public."equipment_status" AS ENUM (
            'Active',       -- участвует
            'Archived'      -- скрыт / не используется
        );
    end if;
END
$$;


-- Дерево оборудования
CREATE TABLE IF NOT EXISTS equipment (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    -- Уникальный идентификатор
    parent_id       BIGINT REFERENCES equipment(id)ON DELETE RESTRICT,      -- Идентификатор родительской ноды
    name            VARCHAR(255) NOT NULL,                      -- Проектное / Системное имя устройста, уникальное как минимум в пределах родителя
    title           VARCHAR(512) NOT NULL,                      -- Название для UI, не требует перевода, поскольку задано пользователем
    status          equipment_status NOT NULL DEFAULT 'Active', -- Статус: `Active` / `Archived`
    attributes      JSONB NOT NULL DEFAULT '{}'::jsonb,         -- Характеристики оборудования
    created         TIMESTAMPTZ NOT NULL DEFAULT Now(),         -- Дата создания записи (сомнительно, можем записать в логи факт создания, если это вообще надо)
    -- Уникальность имени в пределах родителя
    CONSTRAINT equipment_name_unique_per_parent
        UNIQUE (parent_id, name),
    -- JSON должен быть объектом
    CONSTRAINT equipment_attributes_is_object
        CHECK (jsonb_typeof(attributes) = 'object'),
    -- Обязательные идентификационные поля
    CONSTRAINT equipment_attributes_required
        CHECK (
            attributes ? 'serial_number'
            AND attributes ? 'manufacturer'
        ),
    -- Типы обязательных
    CONSTRAINT equipment_attributes_required_types
        CHECK (
            jsonb_typeof(attributes->'serial_number') = 'string'
            AND jsonb_typeof(attributes->'manufacturer') = 'string'
        ),
    -- Даты
    CONSTRAINT equipment_manufacture_date_valid
        CHECK (
            NOT (attributes ? 'manufacture_date')
            OR (attributes->>'manufacture_date')::date <= now()
        ),

    CONSTRAINT equipment_activation_date_valid
        CHECK (
            NOT (attributes ? 'activation_date')
            OR (attributes->>'activation_date')::date <= now()
        ),
    -- Масса
    CONSTRAINT equipment_weight_positive
        CHECK (
            NOT (attributes ? 'weight_kg')
            OR (attributes->>'weight_kg')::numeric > 0
        ),
    -- Габариты
    CONSTRAINT equipment_length_positive
        CHECK (
            NOT (attributes ? 'length_mm')
            OR (attributes->>'length_mm')::numeric > 0
        ),
    CONSTRAINT equipment_width_positive
        CHECK (
            NOT (attributes ? 'width_mm')
            OR (attributes->>'width_mm')::numeric > 0
        ),
    CONSTRAINT equipment_height_positive
        CHECK (
            NOT (attributes ? 'height_mm')
            OR (attributes->>'height_mm')::numeric > 0
        ),
    -- Критичность
    CONSTRAINT equipment_critical_boolean
        CHECK (
            NOT (attributes ? 'critical')
            OR jsonb_typeof(attributes->'critical') = 'boolean'
        ),
    -- Температурный диапазон
    CONSTRAINT equipment_temperature_range_valid
        CHECK (
            NOT (
                attributes ? 'operating_temp_min'
                AND attributes ? 'operating_temp_max'
            )
            OR
            (attributes->>'operating_temp_max')::numeric
                >=
            (attributes->>'operating_temp_min')::numeric
        )
); 
-- Для запросов по родителю (дерево)
CREATE INDEX IF NOT EXISTS idx_equipment_parent
    ON equipment(parent_id);
-- Для запроса по атрибутам
CREATE INDEX IF NOT EXISTS idx_equipment_attributes_gin
    ON equipment USING GIN (attributes);
-- Для запроса по статусу
CREATE INDEX IF NOT EXISTS idx_equipment_status
    ON equipment(status);

-- Докумменты оборудования
CREATE TABLE IF NOT EXISTS documents (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,        -- Уникальный идентификатор
    equipment_id    BIGINT NOT NULL REFERENCES equipment(id) ON DELETE CASCADE, -- указывает на принадлежность оборудованию
    kind            VARCHAR(128),                                   -- Вид документа, пока строка, возможно Паспорт / Тех-документация / Дополнительные..
    name            TEXT NOT NULL,                                  -- Наименование документа, уникально в пределах equipment_id
    path            TEXT NOT NULL,                                  -- Путь к файлу документа
    -- Уникальность имени в пределах экземпляра Оборудования
    CONSTRAINT documents_unique_name_per_equipment
        UNIQUE (equipment_id, name)
);
-- Для запроса документов по оборудованию
CREATE INDEX IF NOT EXISTS idx_documents_equipment
    ON documents(equipment_id);