
-- | Поле          | Тип                                   | Описание                  |
-- | ------------- | ------------------------------------- | ------------------------- |
-- | id            | SERIAL                                | Уникальный идентификатор  |
-- | login         | VARCHAR                               | Логин для авторизации     |
-- | pass          | VARCHAR                               | Хэш пароля                |
-- | name          | VARCHAR                               | ФИО                       |
-- | email         | VARCHAR                               | Электронная почта         |
-- | status        | ENUM('Active', 'Inactive', 'Blocked') | Статус учетной записи     |
-- | created       | TIMESTAMP                             | Дата создания             |
-- | updated       | TIMESTAMP                             | Дата последнего изменения |
-- | deleted       | TIMESTAMP                             | Дата удаления             |

-- CREATE TYPE user_status AS ENUM ('Active', 'Inactive', 'Blocked');

-- Пользователи системы
CREATE TABLE users (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login           VARCHAR(100) NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,
    name            VARCHAR(255),
    email           VARCHAR(320) UNIQUE,
    -- status          user_status NOT NULL DEFAULT 'Active',
    deleted         TIMESTAMPTZ NULL
);

-- Группы безопасности
CREATE TABLE access_group (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(100) NOT NULL UNIQUE
);

-- Принадлежность пользователей группам
CREATE TABLE user_access_group (
    user_id             INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    access_group_id     INT NOT NULL REFERENCES access_group(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, access_group_id)
);

-- Функции безопасности
--   - Виджеты (идентификаторы)
--   - Поведение (идентификаторы)
--   - Данные (название таблиц БД)
CREATE TABLE access_feature (
    id              VARCHAR(128) PRIMARY KEY
    -- description     TEXT,
);

-- Вид доступа (Read - доступ к фичам без права измененять, Write - доступк фичам с правом изменять)
CREATE TYPE access_type AS ENUM ('read', 'write', 'delete');

-- Принадлежность Функции безопасности группам
CREATE TABLE access_feature_group (
    access_feature_id   VARCHAR(128) NOT NULL REFERENCES access_feature(id) ON DELETE CASCADE,
    access_group_id     INT NOT NULL REFERENCES access_group(id) ON DELETE CASCADE,
    access              access_type NOT NULL,
    PRIMARY KEY (access_feature_id, access_group_id, access)
);

-- Для производительности
CREATE INDEX idx_users_id_not_deleted 
    ON users(id)
    WHERE deleted IS NULL;
CREATE INDEX idx_users_login_not_deleted
    ON users(login)
    WHERE deleted IS NULL;

CREATE INDEX idx_user_access_group_user 
    ON user_access_group(user_id);

CREATE INDEX idx_user_access_group_group 
    ON user_access_group(access_group_id);

CREATE INDEX idx_access_feature_group_group 
    ON access_feature_group(access_group_id);

CREATE INDEX idx_access_feature_group_feature 
    ON access_feature_group(access_feature_id);
