
-- Степень износа
CREATE TYPE wear_severity AS ENUM (
    'OK',           -- Норма
    'EARLY',        -- Ранняя стадия дефекта
    'DEVELOPED',    -- Развитый дефект
    'CRITICAL'      -- Критический износ
);

-- Показатели износа
-- | code        | name                    |
-- | ----------- | ----------------------- |
-- | vibration   | Вибрация                |
-- | temperature | Температура             |
-- | load        | Нагрузка                |
-- | speed       | Скорость / Частота      |
-- | lubrication | Смазка                  |
-- | electrical  | Электрические параметры |
-- | structural  | Геометрия / деформация  |
-- 
CREATE TABLE diagnostic_group (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);
